version: '3'
services:
  assets:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/opt/sql-language-server:rw
    command: 'yarn dev' # 'tail -f /dev/null'
    ports:
      - '3000:3000'
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: sqlls
      POSTGRES_PASSWORD: sqlls
    volumes:
      - postgres:/var/lib/postgresql/data
  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: sqlls
      MYSQL_PASSWORD: sqlls
    volumes:
      - mysql:/var/lib/mysql
volumes:
  postgres:
  mysql:
