version: '3'
services:
  example:
    build:
      context: .
      dockerfile: dockerfile_dev_example_server
    command: ''
  assets:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/opt/sql-language-server/rw
    command: 'yarn run watch'
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: