version: '3'
services:
  assets:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/opt/sql-language-server:rw
      # exclude node_modules dir from sharing with host
      - node_modules:/opt/sql-language-server/node_modules
      - node_modules_example:/opt/sql-language-server/example/node_modules
      - node_modules_server:/opt/sql-language-server/packages/server/node_modules
      - node_modules_sqlint:/opt/sql-language-server/packages/sqlint/node_modules
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    command: bash -c "yarn && yarn bootstrap && yarn dev" # tail -f /dev/null
    ports:
      - '3000:3000'
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: sqlls
      POSTGRES_PASSWORD: sqlls
    volumes:
      - postgres:/var/lib/postgresql/data
  mysql:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: sqlls
      MYSQL_PASSWORD: sqlls
    volumes:
      - mysql:/var/lib/mysql
volumes:
  postgres:
  mysql:
  node_modules:
  node_modules_example:
  node_modules_server:
  node_modules_sqlint: