version: '3'
services:
  assets:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/opt/sql-language-server/rw
    command: 'yarn run dev'
    ports:
      - '3000:3000'
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: