module.exports = {
  'SHOW'    : true,
  'DROP'    : true,
  'SELECT'  : true,
  'UPDATE'  : true,
  'CREATE'  : true,
  'DELETE'  : true,
  'INSERT'  : true,
  'REPLACE' : true,
  'EXPLAIN' : true,
  'ALL'     : true,
  'DISTINCT': true,
  'AS'      : true,
  'TABLE'   : true,
  'INTO'    : true,
  'FROM'    : true,
  'SET'     : true,
  'LEFT'    : true,
  'ON'      : true,
  'INNER'   : true,
  'JOIN'    : true,
  'UNION'   : true,
  'VALUES'  : true,
  'EXISTS'  : true,
  'WHERE'   : true,
  'GROUP'   : true,
  'BY'      : true,
  'HAVING'  : true,
  'ORDER'   : true,
  'ASC'     : true,
  'DESC'    : true,
  'LIMIT'   : true,
  'BETWEEN' : true,
  'IN'      : true,
  'IS'      : true,
  'LIKE'    : true,
  'CONTAINS': true,
  'NOT'     : true,
  'AND'     : true,
  'OR'      : true,

  //literal
  'TRUE'    : true,
  'FALSE'   : true,
  'NULL'    : true
};